#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 10 20:54:44 2019

@author: shivam
"""
import turtle
import numpy as np
import pandas as pd

pi_value = []
next_pi_value = []
my_colors = ['#D38C7C', '#DCBE47', '#DCD547', '#B6DC47', '#6BDC47', '#47DCA6', 
             '#47DCD1', '#47B1DC', '#DAB1E8', '#B96D82']

with open("pi1M.txt") as f:
  while True:
    c = f.read(1)
    if not c:
      break
   
    if c != ' ' and c != '\n':
        pi_value.append(int(c))
        
with open("pi1M_next.txt") as f:
  while True:
    c = f.read(1)
    if not c:
      break
   
    if c != ' ' and c != '\n':
        next_pi_value.append(int(c))

k = turtle.Turtle()
k.speed(0)
k.getscreen().bgcolor('#E9E6E6')
k.color('white')
k.penup()
k.sety(-180)
k.pendown()

def flower(t, ourPI):
    for i in ourPI:
        #t.forward(i)
        k.color(my_colors[i])
        t.forward(6*np.sin(i*10))
        t.left(np.sin(i*10))

flower(k, pi_value)

k.done()


#-----------------------------------------------

def draw(t):
    for i in range(10):
        t.circle(10)
        t.penup()
        t.goto(10, 10)
        t.pendown()


draw(k)


turtle.done()

# ------------------------------------
def printPIDig(t, ourPI, nextPI):
    for i in ourPI:
        #t.forward(i)
        t.forward(i)
        t.left(nextPI[i])
         

printPIDig(k, pi_value, next_pi_value)

turtle.done()


# -------------------------------------------------------------------
def flower(t, ourPI):
    for i in ourPI:
        #t.forward(i)
        t.forward(3*np.sin(i*10))
        t.left(np.sin(i*10))

flower(k, pi_value)

#-------------------------------------------------------------------


#try to map with next digit
